version: 0.0
os: linux
files:
  - source: /
    destination: /opt/app/
hooks:
  BeforeInstall:
    - location: scripts/backupAPI.sh
      runas: root
  AfterInstall:
    - location: scripts/installServices.sh
      runas: root
  ApplicationStart:
    - location: scripts/startAPI.sh
      runas: root