CREATE DATABASE IF NOT EXISTS server DEFAULT CHARSET UTF8;

CREATE USER IF NOT EXISTS 'admin'@'localhost' IDENTIFIED BY '12345';

GRANT ALL PRIVILEGES ON server.* TO 'admin'@'localhost';

FLUSH PRIVILEGES;

USE server;

CREATE TABLE IF NOT EXISTS users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    user VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(200) NOT NULL,
    valid_id INT DEFAULT 2
);

CREATE TABLE IF NOT EXISTS stocks (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ticker VARCHAR(6) NOT NULL,
	name VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS dividends (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	stock_id INT NOT NULL,
    value FLOAT NOT NULL,
    date DATETIME NOT NULL,
    user_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS assets (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	stock_id INT NOT NULL,
	amount INT NOT NULL,
    user_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    token varchar(200)
);

CREATE TABLE IF NOT EXISTS types (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);